services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: jajaj1234jajaj
      POSTGRES_USER: postgres
      POSTGRES_DB: ocso_db
    container_name: ocso_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: jajaj1234jajaj
      DATABASE_NAME: ocso_db